### ISSUE TITLE
Настройка и сборка рабочего окружения

### ISSUE THREAD

**Issue by TorinAsakura** [AUAcademy/alfa#1]
Статья с хабра 2018 года, более простой ввод в курс дела, но, более древние зависимости, для ознакомления сойдёт - [Link](https://habr.com/ru/post/350886/)

Более детальное разжёвывание и наиболее подходящий для нас кейс с последними версиями зависимостей и эта статья подойдёт для боевых действий - [Link](https://www.ivarprudnikov.com/static-website-multiple-html-pages-using-webpack-plus-github-example/)

**Comment by Alfa888** [comment]
npm run build-and-beautify - сборка не происходит, директория dist исчезает. Исчезает она из-за этой записи "build-and-beautify": "del-cli dist которая описана в статье.

npm run build сборка тоже не происходит.

**Comment by Alfa888** [comment]
все вышеперечисленное было в package.json

А это код webpack.config.js
const path = require('path');
const ExtractTextPlugin = require('extract-text-webpack-plugin');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const CopyWebpackPlugin = require('copy-webpack-plugin');
const fs = require('fs')

function generateHtmlPlugins(templateDir) {
  const templateFiles = fs.readdirSync(path.resolve(__dirname, templateDir));
  return templateFiles.map(item => {
    const parts = item.split('.');
    const name = parts[0];
    const extension = parts[1];
    return new HtmlWebpackPlugin({
      filename: `${name}.html`,
      template: path.resolve(__dirname, `${templateDir}/${name}.${extension}`),
      inject: false,
    })
  })
}

const htmlPlugins = generateHtmlPlugins('./src/html/views');

module.exports = {
  entry: [
    './src/js/index.js',
    './src/scss/style.scss'
  ],
  output: {
    filename: './js/bundle.js'
  },
  devtool: "source-map",
  module: {
    rules: [{
        test: /\.js$/,
        include: path.resolve(__dirname, 'src/js'),
        use: {
          loader: 'babel-loader',
          options: {
            presets: 'env'
          }
        }
      },
      {
        test: /\.(sass|scss)$/,
        include: path.resolve(__dirname, 'src/scss'),
        use: ExtractTextPlugin.extract({
          use: [{
              loader: "css-loader",
              options: {
                sourceMap: true,
                minimize: true,
                url: false
              }
            },
            {
              loader: "sass-loader",
              options: {
                sourceMap: true
              }
            }
          ]
        })
      },
            {
        test: /\.html$/,
        include: path.resolve(__dirname, 'src/html/includes'),
        use: ['raw-loader']
      },
    ]
  },
  plugins: [
    new ExtractTextPlugin({
      filename: './css/style.bundle.css',
      allChunks: true,
    }),
    new CopyWebpackPlugin([{
        from: './src/fonts',
        to: './fonts'
      },
      {
        from: './src/favicon',
        to: './favicon'
      },
      {
        from: './src/img',
        to: './img'
      },
      {
        from: './src/uploads',
        to: './uploads'
      }
    ]),
  ].concat(htmlPlugins)
};

По статье все перепроверил - не работает.
Нашел видео про веб пак, смотрю пока.

**Comment by TorinAsakura** [comment]
@Alfa888 
1. Используй разметку [markdown и форматирование](https://guides.github.com/features/mastering-markdown/) когда вставляешь код
2. Проверь версии зависимостей, если ты ставил зависимости без указания версий - у тебя не будет работать по той причине, что API свежих версий зависимостей работает иначе, а код, который описан в статье использует старый API

**Comment by Alfa888** [comment]
Thank you.

ср, 18 дек. 2019 г., 2:21 Andrew Ghostuhin notifications@github.com:

**Comment by Alfa888** [comment]
"babel-core": "^6.26.0",
    "babel-loader": "^7.1.4",
    "babel-preset-env": "^1.6.1",
    "clean-webpack-plugin": "^3.0.0",
    "copy-webpack-plugin": "^3.0.0",
    "css-loader": "^3.3.2",
    "del-cli": "^3.0.0",
    "extract-text-webpack-plugin": "^3.0.0",
    "html-cli": "^1.0.0",
    "html-webpack-plugin": "^3.2.0",
    "http-server": "^0.12.0",
    "lodash": "^4.17.15",
    "mini-css-extract-plugin": "^0.8.2",
    "node-sass": "^4.13.0",
    "optimize-css-assets-webpack-plugin": "^5.0.3",
    "raw-loader": "^3.0.0",
    "sass-loader": "^8.0.0",
    "uglifyjs-webpack-plugin": "^2.2.0",
    "webpack": "^4.29.6",
    "webpack-cli": "^3.3.0",
    "webpack-dev-server": "^3.9.0"
Сорри без маркдаун в этот раз выглядит хорошо.
Поменял версии зависимостей на предыдущие. Вобщем не помогло. 
`` build-and-beautify``  удалил и не пользуюсь. Надоело dist восстанавливать каждый раз.
использую только команду `` npm run build`` 
Сборка HTML файла в dist не происходит. Я так понимаю проблема с шаблонизатором, который должен клеить данные в ``index.html`` из ``header.html`` и ``footer.html``
Еще конечно вопрос в том что я меняю версии зависимостей методом тыка. Просто на предыдущие меняю ``npm uninstall ...(было 4.2.2. например)`` ``npm i ...@^3.0.0 (стало)``
а дальше команда ``npm run bild`` и отсутствие результата. 
Точнее мои любимые ошибки:
``npm ERR! code ELIFECYCLE``
``npm ERR! errno 1``
``npm ERR! static-site-webpack-habr@1.0.0 build: `webpack --mode production` ``
``npm ERR! Exit status 1``
``npm ERR!``
``npm ERR! Failed at the static-site-webpack-habr@1.0.0 build script.``
``npm ERR! This is probably not a problem with npm. There is likely additional logging output above.``

**Comment by Alfa888** [comment]
Заработало. Начну вторую статью изучать.

**Comment by TorinAsakura** [comment]
@Alfa888 а код где?

**Comment by Alfa888** [comment]
Код в чат или сборку прямо на гит в директорию? (уточняю что ты имеешь ввиду)

**Comment by Alfa888** [comment]
Папку с модулями node из сборки убрать? Весит много. И в примере ее не было.

**Comment by TorinAsakura** [comment]
Посмотри примера .gitignore по гитхабу…

**Comment by Alfa888** [comment]
Понятно. Чтобы у меня оставалась а на гит не заливалась. 
/node_modules          надеюсь с написанием не ошибся.

**Comment by Alfa888** [comment]
remote: Invalid username or password. Я свои вводил. Не подходит.
